name: Publish image to Docker hub
on:
    workflow_dispatch:
   
                   

  

jobs:
    publich_images:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run:
                ls
            - name: Login to Docker
              uses: docker/login-action@v1
              with:
                username: ${{secrets.DOCKER_HUB_USERNAME}}
                password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

            - name: build image
              run: |
                LATEST_TAG=$(git rev-parse --short HEAD)
                echo $LATEST_TAG  # Use commit hash as a unique tag
                docker build -t edwinasweeney/modelbuild:$LATEST_TAG .
                docker images
                echo "IMAGE_TAG is $LATEST_TAG"
                docker push edwinasweeney/modelbuild:$LATEST_TAG
                
               